brew cleanup \
     aria2 \
     bazaar \
     boot2docker \
     brew-cask \
     closure-compiler \
     curl \
     dnsmasq \
     docker \
     dos2unix \
     editorconfig \
     emacs \
     fasd \
     fish \
     fortune \
     git \
     git-annex \
     git-now \
     lynx \
     mercurial \
     mplayer \
     nginx \
     nmap \
     node \
     nvm \
     p7zip \
     pypy \
     ranger \
     saltstack \
     subversion \
     task \
     terminal-notifier \
     the_platinum_searcher \
     the_silver_searcher \
     tig \
     tmux \
     trash \
     tree \
     vim \
     vit \
     w3m \
     webkit2png \
     weechat \
     wget \
     youtube-dl \
     yuicompressor \
     zsh
brew cask cleanup
