#!/bin/bash
set -e
unset SHELL

sudo -v
while true; do sleep 60; sudo -n true; kill -0 "$$" || exit; done 2>/dev/null &

if ! [ -x "$(command -v salt-call)" ]; then
  if [ -x "$(command -v pacman)" ]; then
    sudo pacman -S --noconfirm --needed salt
  else
    echo 'Error: salt-call is not installed.' >&2
    exit 1
  fi
fi

salt-call --version

sudo salt-call --saltfile=Saltfile ${@:-state.highstate}
